name: dressing_real_first_arm
state_dim: 9  
distilled_features_dim: 66  
action_dim: 3  
obs_dim: ${state_dim}  # Keep for backward compatibility
keypoint_dim: 0
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.dressing_real_dataset.DressingRealDataset
  zarr_path: /scratch/pnt8/dressing_demos/real/Dec31_combined_upsampled_x2.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_key: "state"
  action_key: "action"
  distilled_features_key: "distilled_features"
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
  upsampled: True
  upsample_multiplier: 2