name: dressing_real_first_arm_finetune

obs_dim: 15
action_dim: 2
keypoint_dim: 0
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.dressing_real_dataset.DressingRealDataset
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  num_datasets: 2
  include_datasets: ["sim", "real_first_arm"]
  use_domain_encoding: False  # disabled by default
  domain_encoding_dim: 2
  zarr_configs:
  # Keep sim dataset ONLY for computing normalizer
  - path: /scratch/pnt8/dressing_demos/sim2real/sim/halton_base_dagger_rd2_x1_aligned_upsampled_x4.zarr
    name: sim
    max_train_episodes: 400  # ← SET TO 0! No training data
    sampling_weight: 0.2   # ← SET TO 0! Never sampled
    val_ratio: 0.0         # ← No validation data either
    upsampled: True
    upsample_multiplier: 4
    domain_encoding: [1, 0]
  # Real datasets get all the training weight
  - path: /scratch/pnt8/dressing_demos/sim2real/real/round3+4_data_green_tee_upsampled_x2.zarr    
    name: real_first_arm
    max_train_episodes: null
    sampling_weight: 0.8  # 100% real arm 1
    val_ratio: 0.1
    upsampled: True
    upsample_multiplier: 2
    domain_encoding: [0, 1]