name: dressing_first_arm_real_finetune

obs_dim: 16
action_dim: 2
keypoint_dim: 0
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.dressing_real_lowdim_dataset.DressingRealLowdimDataset
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  num_datasets: 2  # Keep sim for normalization!
  include_datasets: ["sim", "real_first_arm"]
  zarr_configs:
  # Keep sim dataset ONLY for computing normalizer
  - path: /scratch/pnt8/dressing_demos/sim/halton_base_dagger_rd2_x1_aligned_upsampled_x4.zarr
    name: sim
    max_train_episodes: null  # ← SET TO 0! No training data
    sampling_weight: 0.0   # ← SET TO 0! Never sampled
    val_ratio: 0.0         # ← No validation data either
    upsampled: True
    upsample_multiplier: 4
  # Real datasets get all the training weight
  - path: /scratch/pnt8/dressing_demos/real/round3_data_green_tee_upsampled_x2.zarr    
    name: real_first_arm
    max_train_episodes: null
    sampling_weight: 1.0  # 100% real arm 1
    val_ratio: 0.1
    upsampled: True
    upsample_multiplier: 2