name: first_arm_hybrid

shape_meta:
  obs:
    state:
      shape: [10]
      type: low_dim
    image:
      shape: [4, 128, 128]
      type: rgb
  action:
    shape: [3]
obs_eef_target: False

dataset:
  _target_: diffusion_policy.dataset.first_arm_hybrid_dataset.FirstArmHybridDataset
  zarr_path: /scratch/pnt8/first_arm_scene/datasets/depth_halton_n=8_012_50_compressed.zarr
  modalities: ['rgb', 'pos', 'vel', 'force', 'depth']
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_eef_target: ${task.obs_eef_target}
  use_manual_normalizer: False
  seed: 42
  val_ratio: 0.1
